// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evmgchemlurmvlxhnidt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2bWdjaGVtbHVybXZseGhuaWR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA0NzQ1MTQsImV4cCI6MjA1NjA1MDUxNH0.d5P2ys1BYG_jlLOcwG7rmFuX3oVpxK3iZghu1fxt5PU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);